version: "3.6"
services:
  database:
    image: mysql:5.7
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./db:/var/lib/mysql

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - "8080:80"
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - 9000:80
    environment:
      PMA_HOST: database

  wordmove:
    tty: true
    depends_on:
      - wordpress
    image: welaika/wordmove
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./config/.bashrc:/root/.bashrc
      - wordpress:/var/www/html
      - ./config/movefile.yml:/var/www/html/movefile.yml
      - ./wp-content:/var/www/html/wp-content
    working_dir: /var/www/html

volumes:
  wordpress:
