global:
  sql_adapter: wpcli

local:
  vhost: http://localhost:8080
  wordpress_path: <%= ENV['WORDMOVE_WORKDIR'] %> # use an absolute path here

  database:
    name: "wordpress"
    user: "wordpress"
    password: "wordpress"
    host: "database"
    charset: "utf8"

production:
  vhost: https://www.example.com
  wordpress_path: /var/www/html # use an absolute path here

  database:
    name: database_name
    user: user
    password: password
    host: localhost
    # port: 3308 # Use just in case you have exotic server config
    # mysqldump_options: '--max_allowed_packet=1G' # Only available if using SSH
    # mysql_options: '--protocol=TCP' # mysql command is used to import db

  exclude:
    - ".git/"
    - ".gitignore"
    - ".gitmodules"
    - ".env"
    - "node_modules/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "movefile"
    - "movefile.yml"
    - "movefile.yaml"
    - "wp-config.php"
    - "wp-content/*.sql.gz"
    - "*.orig"
    - "wp-content/themes/twenty*/"
    - "wp-content/plugins/hello.php"

  # paths: # you can customize wordpress internal paths
  #   wp_config: /var/www/html/wp-config.php
  #   wp_content: wp-content
  #   uploads: wp-content/uploads
  #   plugins: wp-content/plugins
  #   mu_plugins: wp-content/mu-plugins
  #   themes: wp-content/themes
  #   languages: wp-content/languages

  # ssh:
  #   host: host
  #   user: user
  #   password: password # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: '--verbose --itemize-changes' # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: host
  #     user: user
  #     password: password # password is optional, will use public keys if available.

  # hooks: # Remote hooks won't work with FTP
  #   push:
  #     before:
  #       - command: 'echo "do something"'
  #         where: local
  #         raise: false # raise is true by default
  #     after:
  #       - command: 'echo "do something"'
  #         where: remote
  #   pull:
  #     before:
  #       - command: 'echo "do something"'
  #         where: local
  #         raise: false
  #     after:
  #       - command: 'echo "do something"'
  #         where: remote
  #
  # forbid:
  #   push:
  #     db: false
  #     plugins: false
  #     themes: false
  #     languages: false
  #     uploads: false
  #     mu-plugins: false
  #   pull:
  #     db: false
  #     plugins: false
  #     themes: false
  #     languages: false
  #     uploads: false
  #     mu-plugins: false
# staging: # multiple environments can be specified
#   [...]
